#!/bin/bash
cd F:\courses/QA/Ilona
mkdir homework1sc
cd F:\courses/QA/Ilona/homework1sc
mkdir 1 2 3
cd F:\courses/QA/Ilona/homework1sc/1
touch {newfile1.txt,newfile2.txt,newfile3.txt}
touch {newfile1.json,newfile2.json}
mkdir 1.1 1.2 1.3
ls -la
mv newfile1.json 1.2
mv newfile2.json 1.2
